### ISSUE TITLE
Remove waffle.io badges

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#102]
As I introduced the waffle.io badges and I don't use Waffle.io anymore (I use ZenHub instead), I would vote for removal of the Waffle.io badges from ReadMe.md file.

Any objections?

**Comment by hi5** [comment]
Fine by me - Gitter badge could also go, nobody uses it I think.

**Comment by vasili111** [comment]
No objections by me. If nobody uses Gitter and Waffle.io and nobody is against removing them it is ok to remove.

**Comment by hoppfrosch** [comment]
As there are no more objections I'll remove waffle.io and gitter badges
