### ISSUE TITLE
New items: Documentation in other languages

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#105]
At the moment we only have one link to the official documentation in English. 
There are of course translations in German and Chinese, but there are also translations in Korean, Japanese and Russian. Perhaps links to these "unofficial" resources should be added even if there is no guarantee these will be kept up to date.

**Comment by hi5** [comment]
"Current"

* http://ragnar-f.github.com/docs
* http://ahkcn.sourceforge.net/docs
* http://ahkwiki.net/
* http://ahk-wiki.ru/

Historical

* http://autohotkey.free.fr/docs/

**Comment by vasili111** [comment]
It will be nice to have them in list.

**Comment by joedf** [comment]
I didnt even know about that Russian one.

**Comment by hoppfrosch** [comment]
I also think, this might be useful ...

**Comment by hoppfrosch** [comment]
As there only positives, I'll add it
