### ISSUE TITLE
New item: LBEX

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#106]
### Item to be added:

LBEX
### Author of the new item

[just me](https://github.com/AHK-just-me\)
### Awesome-AHK chapter the item should be added to

Libraries - GUI - Listbox
### Description of the new Item

some functions for ListBoxes
### Discussion Links:

Forum: https://autohotkey.com/boards/viewtopic.php?f=6&t=4755
### Source Links:

Source: https://github.com/AHK-just-me/LBEX

**Comment by joedf** [comment]
Approved 👍 
Totally should have been added a longtime ago without hesitation 😄
