### ISSUE TITLE
New Item: CNG (Cryptography API: Next Generation)

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#111]
### Item to be added:
CNG (Cryptography API: Next Generation)

### Author of the new item
[jNizM](https://github.com/jNizM)

### Awesome-AHK chapter the item should be added to 
Libraries - Maths

### Description of the new Item
Cryptography API: Next Generation (CNG) is the long-term replacement for the CryptoAPI.

### Discussion Links:
Forum: https://autohotkey.com/boards/viewtopic.php?f=6&t=23413

### Source Links: 
Source: https://github.com/jNizM/AHK_CNG

**Comment by Masonjar13** [comment]
Correct. Block encryption still needs to be done. Currently, it only contains hash methods.

**Comment by hoppfrosch** [comment]
When is a library containing function collections considered to be ready? Is supplying "hash methods only" not useful enough, to be added to our list?

**Comment by Masonjar13** [comment]
Well first, there's no need to be so defensive; neither of us said it shouldn't be added. Second, it's quite useful. I made my own fork when he started working on it, making an object available quite a bit before he made his.

Why don't you submit a pull request?

**Comment by joedf** [comment]
Approved.

**Comment by hoppfrosch** [comment]
@masonjar13: I haven't meant to be defensive - I just wanted to ask for criteria, when a library is considered to be finished and therefore worth being added to the list ...

What's the sense of a pull request for me, as I was the main maintainer of this list during the last months? After creating a pull request, I would most likely have been the one who merges it in as well (potentially without any discussion)... As we don't have any rules about who is "allowed" to merge pull request (or how many approvers are needed before merging a pull request), I thought it's more democratic to start a discussion via thread about new items to add.  And even if any other would have rejected my pull request, I would have done the work creating the pull request in vain.

**Comment by joedf** [comment]
For most, nothing complex is needed. Only the main idea is needed.
@hoppfrosch Your methodology is the most sensible and is a good common practice.
