### ISSUE TITLE
[Library] Edit v2.0 - Update and Manage any Edit Control

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#115]
### Item to be added:
[Edit v2.0 - Update and Manage any Edit Control](https://autohotkey.com/boards/viewtopic.php?f=6&t=5063)

### Author of the new item
[jballi](https://autohotkey.com/boards/memberlist.php?mode=viewprofile&u=58)

### Awesome-AHK chapter the item should be added to 

* Libraries - GUI - Edit

### Description of the new Item
Library for the lightweight and surprisingly powerful default Edit control for displaying and editing text. 

### Discussion Links:
Forum: https://autohotkey.com/boards/viewtopic.php?f=6&t=5063

### Source Links: 

* Source: https://dl.dropboxusercontent.com/u/225589492/AutoHotkey%20Forum/Edit/v2.0/Edit.zip
* Documentation: https://dl.dropboxusercontent.com/u/225589492/AutoHotkey%20Forum/Edit/v2.0/Edit%20Library.html

**Comment by joedf** [comment]
Approved.
