### ISSUE TITLE
Use unique anchor tags for each item in the table of contents

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#12]
Be sure to use unique anchor tags for each item in the table of contents, I've fixed it by adding the category prefix e.g. scripts-clipboard, scripts-gui etc. Simply create a named anchor like so:

    <a name="scripts-gui"></a>

**Comment by rshipp** [comment]
This issue is linked in contributing.md, can it be closed now?

**Comment by vasili111** [comment]
I think yes. If someone will need it we can reopen it.

**Comment by hoppfrosch** [comment]
Added all missing anchor tags
