### ISSUE TITLE
New Item: QuickAccessPopup

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#125]
### Item to be added:
QuickAccessPopup

### Author of the new item
Jean Lalonde

### Awesome-AHK chapter the item should be added to 
Scripts - Filesystem

### Description of the new Item
Multi purpose launcher and file switcher

### Source Links: 
Source: http://www.quickaccesspopup.com

**Comment by hoppfrosch** [comment]
I use this a lot - and I love it ....

**Comment by revug** [comment]
I agree

**Comment by joedf** [comment]
I thought it was already, but no... I've added it.
