### ISSUE TITLE
New item: Time() - Count Days, hours, minutes, seconds between dates 

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#126]
### Item to be added:

Time()

### Author of the new item

[HotKeyIt](https://github.com/HotKeyIt)

### Awesome-AHK chapter the item should be added to 

Libraries - Maths

### Description of the new Item

Count Days, hours, minutes, seconds between dates 

### Discussion Links:
Forum: https://autohotkey.com/board/topic/42668-time-count-days-hours-minutes-seconds-between-dates/

### Source Links: 
Source: https://autohotkey.com/board/topic/42668-time-count-days-hours-minutes-seconds-between-dates/

**Comment by hoppfrosch** [comment]
:+1: - Looks fine - well done function

**Comment by joedf** [comment]
Approved. 👍

**Comment by joedf** [comment]
Added. Commit: https://github.com/ahkscript/awesome-AutoHotkey/commit/6c59274aa12259aa19f7f568eca29e7a3ccb5a76

**Comment by hi5** [comment]
I've used in my CL3 app so slightly embarrassed I didn't mention it earlier 😺

**Comment by joedf** [comment]
Haha no problem ;)

On Feb 20, 2017 1:01 PM, hi5 <notifications@github.com> wrote:

I've used in my CL3 app so slightly embarrassed I didn't mention it earlier 😺

**Comment by hoppfrosch** [comment]
Hmmmm ... @joedf: Why did you close this bug? Either I don't get the point it was closed (due to my missing sense of fine details in english language) - or the issue was closed by accident ....
