### ISSUE TITLE
Rendering of README.MD changed? (no list)

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#132]
For me the table of contents list no longer shows correctly in readme.md 
Is it just me or does anybody else see it like this as well?:

![toc](https://cloud.githubusercontent.com/assets/1973899/24871147/ff95b02c-1e18-11e7-96e2-b7ece311749f.png)

**Comment by hoppfrosch** [comment]
Same here - haven't noticed yet. The rendering has to be changed by github ... as there weren't commits lately (at öeast from me)

**Comment by hoppfrosch** [comment]
There seem to have been problems rendering in certain cases when a \<br\> was used :-(

Removed all \<br\> from README.md

Issue closed

**Comment by joedf** [comment]
Cool 👍
