### ISSUE TITLE
New Item: MagicBox

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#134]
### Item to be added:
MagicBox

### Author of the new item
[Alguimiist](https://autohotkey.com/boards/memberlist.php?mode=viewprofile&u=64723)

### Awesome-AHK chapter the item should be added to 
Tools - GUI WYSIWYG Builders

### Description of the new Item
MagicBox is a development tool to assist in the creation of message boxes.

### Discussion Links:
Forum: https://autohotkey.com/boards/viewtopic.php?p=100953#p100953

### Source Links: 
Source: https://autohotkey.com/boards/viewtopic.php?p=100953#p100953

**Comment by joedf** [comment]
Approved.
