### ISSUE TITLE
New item: Particle System 2.0 

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#135]
### Item to be added:
Particle System 2.0 

### Author of the new item
tidbit

### Awesome-AHK chapter the item should be added to 
Libraries - Graphics

### Description of the new Item
A simple class to add particles to your GUI or onto your screen, using GDI+ .

### Discussion Links:
https://autohotkey.com/boards/viewtopic.php?f=6&t=26485

### Source Links: 
https://github.com/acorns/Particle-System

**Comment by joedf** [comment]
Approved.
