### ISSUE TITLE
New item: AEI - AutoHotkey Environment Information 

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#136]
### Item to be added:
AEI - AutoHotkey Environment Information 

### Author of the new item
joedf

### Awesome-AHK chapter the item should be added to 
Tools - Others

### Description of the new Item
Displays AutoHotkey Environment Information and AHK support relevant System Information with a fancy update checker that auto-downloads with a progress bar. 

### Discussion Links:
https://autohotkey.com/boards/viewtopic.php?f=6&t=5825

### Source Links: 
https://github.com/joedf/AEI.ahk

**Comment by joedf** [comment]
Haven't even thought of adding this. Cool. I just feel it's kind of biased if I am the only one approving this.
Due to the forums' acceptance (quite a few users) and lack of response I assume this is fine.
Approved. 👍

**Comment by hoppfrosch** [comment]
Credit where credit is due. :wink:

**Comment by joedf** [comment]
haha awesome 👍
