### ISSUE TITLE
New item: Class_ScrollGUI

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#137]
### Item to be added:
Class_ScrollGUI

### Author of the new item
just me

### Awesome-AHK chapter the item should be added to 
Libraries - GUI

### Description of the new Item
Creates a scrollable GUI as a parent for AHK GUI windows.

### Discussion Links:
https://autohotkey.com/boards/viewtopic.php?f=6&t=6316

### Source Links: 
https://github.com/AHK-just-me/Class_ScrollGUI

**Comment by joedf** [comment]
Approved.
