### ISSUE TITLE
Remove item: AHKScript.org

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#138]
### Item to be removed:
ahkscript,org

### Reason:
obsolete - since ahkscript.org has been reunited with autohotkey.com again.

#### Caveat:
**Be sure not to loose the AutoHotkey Foundundation LLC -Link!!!!**

**Comment by joedf** [comment]
I agree somewhat, but I would leave it for now as we never if it might change, but yes ahkscript.org is now dedicated to foundation stuff. Really, I am not even sure. Maybe both should be there anyway? ahaha

**Comment by revug** [comment]
>  but I would leave it for now...
Maybe now it is time to do it?

**Comment by revug** [comment]
It is still here: https://github.com/ahkscript
![Screenshot_6](https://user-images.githubusercontent.com/82271055/141322193-a030e296-8acc-4d8e-8123-b95280db3fe5.jpg)

**Comment by joedf** [comment]
That's fine, we have 2. One is /autohotkey and this one /ahkscript. One is for official code, the other is a mix of official and community code.

**Comment by revug** [comment]
Joe, I mean the link http://ahkscript.org/ that is in the description of the https://github.com/ahkscript. I've highlighted it via red square on my screenshot. As we know this link redirects to https://www.autohotkey.com/, so it might be replaced with the second one.

**Comment by joedf** [comment]
@revug yes, exactly. I think I'll leave as it, it redirects to autohotkey.com... I don't really too strongly either way.
