### ISSUE TITLE
New item: AHK-EXE-Swapper

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#139]
### Item to be added:
AHK-EXE-Swapper. 

### Author of the new item
evilC

### Awesome-AHK chapter the item should be added to 
Tools - Others

### Description of the new Item
Swap AHK version quickly! 

### Discussion Links:
https://autohotkey.com/boards/viewtopic.php?f=6&t=6310

### Source Links: 
https://autohotkey.com/boards/viewtopic.php?f=6&t=6310

**Comment by joedf** [comment]
Approved.
