### ISSUE TITLE
5x DSV - Libraries - Data-format

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#145]
Libraries - Data-format would be a category that might work or perhaps Database.

They are very similar but each has their own set of functions, so either add all <strike>three</strike> four or none.

* [AHK_ctable](https://github.com/hoppfrosch/AHK_cTable) - by hoppfrosch - Library to handle strings in tabular format - Forum thread: [link](https://autohotkey.com/board/topic/61256-object-table/://autohotkey.com/board/topic/61256-object-table/page-2?&#entry467816).
* [CSV](https://github.com/hi5/CSV) - by trueski/kdoske - Library to work with CSV files and Listview functions. Forum thread: [link](https://autohotkey.com/boards/viewtopic.php?f=6&t=34853).
* [List manipulation functions](http://www.hars.us/SW/List.ahk) - by Laszlo - Function library to manipulate comma delimited lists. Forum thread: [link](https://autohotkey.com/board/topic/3020-list-manipulation-functions/).
* [Table](https://github.com/Jim-VxE/AHK-Lib-Table) - by VxE - Library to manipulate strings in tabular (TSV) format  and Listview functions. Forum thread: [link](https://autohotkey.com/board/topic/61540-lib-string-based-table-manipulation-v028/).
* [ObjCSV](https://github.com/JnLlnd/ObjCSV/) - by JnLlnd - Library to load/save CSV files to Objects and  and Listview functions. Forum thread: [link](https://autohotkey.com/boards/viewtopic.php?f=6&t=41).

**Comment by hoppfrosch** [comment]
Just to throw my hat in the Ring:

- [AHK_ctable](https://github.com/hoppfrosch/AHK_cTable) - by hoppfrosch - Library to handle strings in tabular format - Forum thread: [link](https://autohotkey.com/board/topic/61256-object-table/://autohotkey.com/board/topic/61256-object-table/page-2?&#entry467816)

**Comment by vasili111** [comment]
There is also "Lists" category which has lists manipulation library. Should we keep all types of data formats libraries together?

**Comment by hi5** [comment]
In that case lists as category could be removed and the entry there moved to data-format as well.

**Comment by hi5** [comment]
Done - see https://github.com/ahkscript/awesome-AutoHotkey/pull/159
