### ISSUE TITLE
New Item: ClassMemory

### ISSUE THREAD

**Issue by G33kDude** [ahkscript/awesome-AutoHotkey#150]
### Item to be added:
ClassMemory

### Author of the new item
[RHCP (Kalamity)](https://github.com/Kalamity/classMemory)

### Awesome-AHK chapter the item should be added to 
I don't think it fits into any existing category. Does a new one need to be created?

### Description of the new Item
Lets you scan and edit other processes' memory, Cheat Engine style

### Discussion Links:
Forum: https://autohotkey.com/boards/viewtopic.php?t=1177

### Source Links: 
Source: https://github.com/Kalamity/classMemory

**Comment by vasili111** [comment]
:+1: 
I have personally used it. It is very powerful and useful.

**Comment by G33kDude** [comment]
If this library is to be added it should belong to a section titled like "Memory". However, it is such a definitive and complete library that I suspect we won't see any additions to that section for quite some time. To further inform whether to create a new section I have two questions to ask of whoever can answer them:

1. Are there any other sections/categories that a library like ClassMemory could fit into.
2. Are there any other libraries that should be on this list which would go into the same category as ClassMemory?

**Comment by joedf** [comment]
@G33kDude Agreed...
Either we make a new section like the lonely libraries:Filesystem or we put it under libraries:System... :/
I say we just make a new section.

**Comment by G33kDude** [comment]
The System section seems more applicable to libraries that interact with Windows directly. ClassMemory uses Windows, yes, but to interact with other applications not Windows itself.

Another lonely section it is then. Hopefully something will come along soon to join it! I'll leave this issue open for a week to gather further ideas and if nothing decisive comes along I'll create the new section.
