### ISSUE TITLE
Can't create a new script

### ISSUE THREAD

**Issue by pikachu292** [ahkscript/awesome-AutoHotkey#151]
I was following the beginner tutorial and got to the part where you make a script. But when I right click and mouse over new the "AutoHotkey Script" isn't there.

**Comment by pikachu292** [comment]
Nvm got it to work somehow

**Comment by hi5** [comment]
You can just create a script in Notepad and save it as `script.ahk` (don't forget to type the .ahk extension, and to make sure it is not saves as `script.ahk.txt` by mistake)

To help you write scripts there are several editors that will make it a lot easier, you can find them here https://autohotkey.com/boards/viewforum.php?f=60 - AHK Studio and SciTE4AutoHotkey are very suitable as they show tips while you write your code to assist you.
