### ISSUE TITLE
CL3 - clipboard manager

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#152]
I think it is stable enough to share, but will leave it up to other to decide if it should be added :-)

### Item to be added:
CL3 

### Author of the new item
[hi5](https://github.com/hi5)

### Awesome-AHK chapter the item should be added to 
Scripts - Clipboard

### Description of the new Item
A clipboard manager (text only) with plugins (Search, predefined Slots, ClipChain, FIFO, Editor and more)

### Discussion Links:
Forum: https://autohotkey.com/boards/viewtopic.php?f=6&t=814

### Source Links: 
Source: https://github.com/hi5/CL3

**Comment by joedf** [comment]
This should have been in there long ago ;)
Add it in @hi5  👍

**Comment by hi5** [comment]
Oh well if you insist :-)

**Comment by joedf** [comment]
oh youuuu :information_desk_person: 😉
