### ISSUE TITLE
Visual Studio Code for AutoHotkey - Setup for AutoHotkey in VSCode 

### ISSUE THREAD

**Issue by mstenemo** [ahkscript/awesome-AutoHotkey#154]
### Item to be added:
VSCode Integrated Development Environment implementation for AutoHotkey 

### Author of the new item
[Stef-levesque](https://github.com/stef-levesque)

### Awesome-AHK chapter the item should be added to 
Tools - Integrated Development Environment 

### Description of the new Item
Setup for code editor VSCode for AutoHotkey.

### Discussion Links:
https://autohotkey.com/boards/viewtopic.php?t=12525

### Source Links: 
Source: https://github.com/stef-levesque/vscode-autohotkey

**Comment by joedf** [comment]
Definitely add this in, I would link to the vscode marketplace page too: https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-autohotkey
Make a pull request and I'll merge it. 👍
