### ISSUE TITLE
New Item: ahk - A Python wrapper for AutoHotkey

### ISSUE THREAD

**Issue by spyoungtech** [ahkscript/awesome-AutoHotkey#167]
### Item to be added:
ahk

### Author of the new item
[spyoungtech](https://github.com/spyoungtech)

### Awesome-AHK chapter the item should be added to 
Tools - (Use in) other programming languages

### Description of the new Item
A Python wrapper for AutoHotkey.

### Discussion Links:
Forum: https://www.autohotkey.com/boards/viewtopic.php?f=6&t=63184

### Source Links: 
Source: https://github.com/spyoungtech/ahk

**Comment by spyoungtech** [comment]
There are two existing Python-related utilities already on the list, however, they are quite dated, no longer maintained, and built for Python2 only, which will be End-of-life this year. This tool is new, actively developed and maintained, and works with modern versions of Python.

I've not yet reached a 1.0 release on this project yet, but it is relatively stable and has some automated testing already. Works with most recent version of AutoHotkey and I also plan to support V2 after its release.

**Comment by ttnnkkrr** [comment]
P0

**Comment by joedf** [comment]
Great work! 👍 
Make a short post of it in the forum; at least a mention and I'll merge it right away.
If you really don't want to... that's fine, but it would be great for completeness. 🍰

**Comment by spyoungtech** [comment]
Went ahead and made forum post @joedf and updated the above. Will update PR shortly.

**Comment by spyoungtech** [comment]
PR updated and ready.

**Comment by joedf** [comment]
Awesome! Merged.
