### ISSUE TITLE
add "CodeQuickTester"

### ISSUE THREAD

**Issue by G33kDude** [ahkscript/awesome-AutoHotkey#28]
I want to add my [code tester](http://ahkscript.org/boards/viewtopic.php?f=6&t=6113) but I can't find a good section to put it in. It is a development tool, but it's hardly an integrated development environment.

**Comment by joedf** [comment]
Tools -> others

**Comment by vasili111** [comment]
I agree with **joedf**. I think *Tools -> others* is good place for [code tester](http://ahkscript.org/boards/viewtopic.php?f=6&t=6113) .
