### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by arthurvr** [ahkscript/awesome-AutoHotkey#30]
This repo seems to miss a license. https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license :)

**Comment by hi5** [comment]
Perhaps adding the same license as https://github.com/bayandin/awesome-awesomeness:
```
## License

[![Creative Commons License](http://i.creativecommons.org/l/by/4.0/88x31.png)](http://creativecommons.org/licenses/by/4.0/)

This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).
```

:question:

**Comment by arthurvr** [comment]
Lgtm

**Comment by vasili111** [comment]
Yes it definitely needs license. I added "Creative Commons Attribution 4.0 International License" as it was suggested. We can also add other licenses if you think is necessary.

**Comment by arthurvr** [comment]
Yay! Thanks :)

**Comment by joedf** [comment]
Very nice :+1:

**Comment by vasili111** [comment]
I think that we can have several licences. What about adding [Public domain](https://creativecommons.org/publicdomain/zero/1.0/) too?
