### ISSUE TITLE
HotClass / CvJoyInterface

### ISSUE THREAD

**Issue by evilC** [ahkscript/awesome-AutoHotkey#33]
Hi, whilst I appreciate inclusion in your curated list, HotClass was an experiment that never really reached maturity.

I have recently started work on a replacement for the hotkey GuiControl, which utilizes the same SetWindowsHookEx technique, but the code is more refined and ready for deployment.
There is currently no documentation, and it is still maybe a little immature, but it's still better than the default AHK hotkey guicontrol (eg it supports mouse buttons).
https://github.com/evilC/CHotkeyControl

Also, seeing as AHK does not support Joystick Output, might I also recommend for inclusion my vJoy feeder library CvJoyInterface. This allows you to control a vJoy virtual joystick with AHK. It's super easy to use and is well documented.
https://github.com/evilC/AHK-CvJoyInterface

**Comment by joedf** [comment]
Go ahead ;)

**Comment by vasili111** [comment]
Nice :)

https://github.com/ahkscript/awesome-AutoHotkey/commit/a263c74c2eb9462d4ee6717542007c6da8e25a75

https://github.com/ahkscript/awesome-AutoHotkey/commit/00545693b125b7456ec36ce82a499d93cf6b4c8f

https://github.com/ahkscript/awesome-AutoHotkey/commit/e925aa503f92b4f04acfa5061037025641775f56
