### ISSUE TITLE
Why two commits have unknowns author. Why?

### ISSUE THREAD

**Issue by vasili111** [ahkscript/awesome-AutoHotkey#36]
There are two commits (https://github.com/ahkscript/awesome-AutoHotkey/commit/70066eaeec5c9a917692054ce5846a5b7cd03024 and https://github.com/ahkscript/awesome-AutoHotkey/commit/4d0e7583ddc8c16e318e32507d135231881eb68c) that have *unknown* author. Why it is so? Is this some kind of bug?

**Comment by arthurvr** [comment]
Not a bug just a bad git config of the contributor.

**Comment by joedf** [comment]
Suspicious, just a little. who?

**Comment by rshipp** [comment]
If you check the question mark icon next to "unknown" in the commit page, it tells you the email address. It's just not associated with a github account, probably because someone forgot to set up their config correctly.

**Comment by joedf** [comment]
... -,-

**Comment by rshipp** [comment]
That's what we get for giving everyone direct access to the repo :)

**Comment by joedf** [comment]
lol. :p
