### ISSUE TITLE
Why commit 70066ea was reverted with 4d0e758 ?

### ISSUE THREAD

**Issue by vasili111** [ahkscript/awesome-AutoHotkey#37]
I think commit 70066ea is useful because it adds html anchors that are needed and puts *Decompilers* in right alphabetical order. So why commit 70066ea  was reverted with 4d0e758 ?

**Comment by arthurvr** [comment]
Because GitHub adds those automatically.

**Comment by vasili111** [comment]
@arthurvr Please read https://github.com/ahkscript/awesome-AutoHotkey/issues/12 .

**Comment by hoppfrosch** [comment]
That was me - I tried to fix #12, but the fix does not work. Therefore I revert the non-working bugfix. I'll try to get a working fix.

Currently I don't understand completely why some links are working - and others don't.

**Comment by vasili111** [comment]
@hoppfrosch 
What you mean by "some links are working - and others don't"? Which links are not working?

**Comment by hoppfrosch** [comment]
Can't remember which links stopped working, but not all links worked ....

As I introduced this commit, I reverted it until I find a working solution (or anybody else will find it ...)
