### ISSUE TITLE
Data format - suggestions

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#38]
I saw @hoppfrosch added a new section "Data format" 

Not sure if these two fit there :question: 

* [AutoHotkey Object - XML](https://github.com/hi5/CL3/blob/master/lib/XA.ahk) by trueski - Save and load AutoHotkey objects (Arrays) in XML format. Forum [link](http://www.autohotkey.com/board/topic/85461-ahk-l-saveload-arrays/)

Note: link to my repo as that has a working version, the code on ahk . com is messed up due to forum upgrade AND it has a additional function to clean invalid characters https://github.com/hi5/CL3/blob/master/lib/XA.ahk#L172 

* [ObjDump / ObjLoad](http://ahkscript.org/boards/viewtopic.php?f=6&t=3573) by HotKeyIt - Read and write AutoHotkey objects (Arrays) from / to binary file. Forum [link](http://ahkscript.org/boards/viewtopic.php?f=6&t=3573)

**Comment by joedf** [comment]
Seems reasonable

**Comment by hoppfrosch** [comment]
I'll add them - I'd planned anyway to add a XML-Library.

Wasn't quite sure whether "data formats" is a reasonable title - but I didn't find any better
