### ISSUE TITLE
Connect awesome-Autohotkey with waffle.io

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#39]
[Waffle.io](https://waffle.io/) offers a cute graphical interface to work with github-issues (like [trello](https://trello.com/)). It's more intuitive to work with issues via waffle.io

The connection between waffle.io and awesome Autohotkey has to be established by an admin og the github organization ahkscript ....

See: https://github.com/waffleio/waffle.io/wiki/FAQs#add-new-board

**Comment by joedf** [comment]
https://waffle.io/ahkscript/awesome-AutoHotkey
?like that, not sure I got it :p

**Comment by hoppfrosch** [comment]
You .... got it! ;-) Thx

**Comment by hoppfrosch** [comment]
You .... got it! ;-) Thx
