### ISSUE TITLE
Change the order of badges

### ISSUE THREAD

**Issue by vasili111** [ahkscript/awesome-AutoHotkey#43]
I have changed the order of badges. I think that way they are more structured.
I think that `gh` badge should come first because it is in fact copy of awesome list. Next should come badges that are associated with awesome-Autohotkey list (`gitter` and `waffle`). And after should come all other badges. 
What you think about it?

**Comment by rshipp** [comment]
:+1:

**Comment by joedf** [comment]
perfect.
