### ISSUE TITLE
New library: TaskDialog

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#49]
Add new entry to libraries-GUI-????:
TaskDialog by just Me

Forum: http://ahkscript.org/boards/viewtopic.php?f=6&t=4635
Source: https://github.com/AHK-just-me/TaskDialog

**Comment by hoppfrosch** [comment]
Not quite sure, what's an appropriate subsection, where the item could be added

**Comment by hoppfrosch** [comment]
Perhaps it's worth to add a second implementation:
TskDlg by cocobelgia

Source: https://github.com/cocobelgica/AutoHotkey-Util/blob/master/TskDlg.ahk

**Comment by hoppfrosch** [comment]
... or even a third implementation:
TaskDialog by TheGood

Forum: http://www.autohotkey.com/board/topic/54555-taskdialog-stdlib-compatible/
Source: https://github.com/jleb/TaskDialog

**Comment by perfaram** [comment]
Well, the more the merrier... But OP's library is really good, and the other ones don't even have a README.

**Comment by hoppfrosch** [comment]
Hmmm... which one is meant with "OP's library"?

**Comment by hoppfrosch** [comment]
Hmmm... which one is meant with "OP's library"?

**Comment by perfaram** [comment]
OP = Original Poster
Well, I didn't notice you're not the one who wrote the library, my mistake.
So, I meant : https://github.com/AHK-just-me/TaskDialog

**Comment by hoppfrosch** [comment]
Result: Adding *TaskDialog by JustMe*

**Comment by hoppfrosch** [comment]
As there are no further objections/remarks, I'll add justMe's library to **libraries-GUI-General**
