### ISSUE TITLE
New library: OnWin

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#50]
Add new entry to libraries-GUI-General:
OnWin by cocobelgica

Source: https://github.com/cocobelgica/AutoHotkey-Util/blob/master/TskDlg.ahk
Forum: http://http://ahkscript.org/boards/viewtopic.php?f=6&t=6463

**Comment by joedf** [comment]
I'm sure you meant the source link to be: https://github.com/cocobelgica/AutoHotkey-Util/blob/master/OnWin.ahk
Anyhow, approved. :+1:

**Comment by hoppfrosch** [comment]
Yes - you're right. For sure OnWin-Source was meant ....
