### ISSUE TITLE
New tool: Yunit

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#51]
Add new entry to Tools-Debugging(?)
Yunit by uberi and infogulch - Super simple unit testing framework for AutoHotkey.

Source: https://github.com/Uberi/Yunit

**Comment by hoppfrosch** [comment]
Perhaps section "Tools-Debugging" should be renamed to "Tools-Debugging & Testing"

**Comment by joedf** [comment]
Approved. :+1:
