### ISSUE TITLE
New library: SerDes

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#52]
Add new entry to libraries-Data format:
**SerDes** by cocobelgica

Serialize / de-serialize an AutoHotkey object structure.

Forum: http://ahkscript.org/boards/viewtopic.php?f=6&t=4212&hilit=SerDes
Source: https://github.com/cocobelgica/AutoHotkey-SerDes

**Comment by hoppfrosch** [comment]
As there are either more approvals nor any objections, this entry should be added

**Comment by joedf** [comment]
Done. :+1:

**Comment by hoppfrosch** [comment]
Thanks - I would have done it as soon as I've got enough time and motivation ... :-)

**Comment by joedf** [comment]
That's fine hahah
Same here :wink:
