### ISSUE TITLE
Scripts > Mouse > Mouse Gesture Script

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#53]
This looks like one of the more complete mouse gesture scripts I've seen (not that I've looked at many)

English introduction here 
https://ayuanx.wordpress.com/2011/09/16/mouse-gesture-english-for-autohotkey/

Japanese homepage latest version:
http://hp.vector.co.jp/authors/VA018351/mglahk.html

Download link of latest version (don' t worry script also in English):
http://www.vector.co.jp/download/file/winnt/util/fh633547.html
(big green download button)

Script includes an English CHM help file.

Should it be added under Scripts > Mouse > Mouse Gesture Script like so

    * [MouseGestureL](http://www.vector.co.jp/download/file/winnt/util/fh633547.html) - Control all of the applications by mouse gesture, gestures and actions defined via customizable interface. Documentation in English and Japanese - Japanese Homepage [link](http://hp.vector.co.jp/authors/VA018351/mglahk.html)

Shown as:

* [MouseGestureL](http://www.vector.co.jp/download/file/winnt/util/fh633547.html) - Control all of the applications by mouse gesture, gestures and actions defined via customizable interface. Documentation in English and Japanese - Japanese Homepage [link](http://hp.vector.co.jp/authors/VA018351/mglahk.html)

**Comment by hoppfrosch** [comment]
+1

**Comment by joedf** [comment]
Go right ahead and add it ;)
