### ISSUE TITLE
New Category: HTTP server or Network?

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#57]
We already have [#Sockets](https://github.com/ahkscript/awesome-AutoHotkey#sockets) of course, but we have several HTTP servers Sparrow #56 and [AHKhttp](https://github.com/Skiouros/AHKhttp)

**Comment by joedf** [comment]
How about rename "Sockets" to "Sockets and Servers"...
Or more simply "Networking" ?

**Comment by hi5** [comment]
"Networking" might be best, there are a few TCP/IP and chat scripts that might be useful to list as well.
