### ISSUE TITLE
Typing: Thumbscript, half-qwerty

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#60]
I suggest we add these two innovative (I think so) typing scripts to Typing.

Thumbscript
http://autohotkey.com/board/topic/27198-beta-thumbscript-ahk/

Half-QWERTY: One-handed Typing
http://autohotkey.com/board/topic/1257-half-qwerty-one-handed-typing/page-6#entry216183

**Comment by joedf** [comment]
You have my approval :+1:

**Comment by hi5** [comment]
Done :-)
