### ISSUE TITLE
New Library: Menu

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#68]
Add new entry to libraries-GUI-Menu:
Menu by just_me

some functions related to AHK menus

Forum: https://www.autohotkey.com/boards/viewtopic.php?t=3068
Source: https://www.autohotkey.com/boards/viewtopic.php?t=3068

**Comment by joedf** [comment]
done :)

**Comment by hoppfrosch** [comment]
Thanks!

Opening new items by myself does not mean I don't want to add them - I just want to hear if others also think it worth adding the items  ;-) - thanks for adding them anyway!

**Comment by joedf** [comment]
Oh ok, haha :)
I thought both were just fine :+1:
