### ISSUE TITLE
Change links from ahkscript.com to autohotkey.com

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#70]
Due to the migration from ahkscript.com to autohotkey.com the links within the listshould be updated

Also the protocol within the links should be changed from http to https

Opinions?

**Comment by hoppfrosch** [comment]
The points above are also reported by awesome_bot (see #66): https://github.com/ahkscript/awesome-AutoHotkey/pull/72

**Comment by joedf** [comment]
Make everything `https://autohotkey.com/*`.
It's time to merge everything back. :+1:

**Comment by hi5** [comment]
I'll have a go at it later today

**Comment by joedf** [comment]
Thanks to @hi5 :smiley:

**Comment by hoppfrosch** [comment]
Hi guys - happy new year to you all!

It seems you're as motivated as myself to bring things forward this year!
Thanks for fixing this issue ... ;-)

**Comment by vasili111** [comment]
Happy new year to all :)

**Comment by joedf** [comment]
Ditto :)
