### ISSUE TITLE
New item: LV_Rows

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#79]
### Item to be added:
Class_LV_Rows

### Author of the new item
[Pulover](https://github.com/Pulover)

### Awesome-AHK chapter the item should be added to 
Libraries - GUI - Listview

### Description of the new Item
Additional functions for AHK ListView controls

### Discussion Links:
Https://autohotkey.Com/boards/viewtopic.Php?F=6&t=137

### Source Links: 
https://github.com/Pulover/Class_LV_Rows

**Comment by joedf** [comment]
Approved :white_check_mark:
