### ISSUE TITLE
New item: Rebar

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#80]
### Item to be added:
`Class_Rebar`

### Author of the new item
[Pulover](https://github.com/Pulover)

### Awesome-AHK chapter the item should be added to 
~~Libraries - GUI - Listview~~
`Libraries - Gui - Custom Controls`

### Description of the new Item
AHK class for AutoHotkey Rebar custom controls 

### Discussion Links:
https://autohotkey.com/boards/viewtopic.php?f=6&t=139

### Source Links: 
https://github.com/Pulover/Class_Rebar

**Comment by joedf** [comment]
I'd put this in `Libraries - GUI - Toolbar` :white_check_mark:

**Comment by hoppfrosch** [comment]
According to suggestion in #81, we should put this under
Libraries - Gui - Custom Controls
