### ISSUE TITLE
New item: Toolbar

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#81]
### Item to be added:
Class Toolbar

### Author of the new item
[Pulover](https://github.com/Pulover)

### Awesome-AHK chapter the item should be added to 
~~Libraries - GUI - Listview~~
Libraries - Gui - Custom Controls

### Description of the new Item
AHK Class for AutoHotkey Toolbar custom controls 

### Discussion Links:
https://autohotkey.com/boards/viewtopic.php?f=6&t=138

### Source Links: 
https://github.com/Pulover/Class_Toolbar

**Comment by joedf** [comment]
:white_check_mark: Good to go! except, maybe put it in its own section?
`Libraries - GUI - Toolbar`

**Comment by Pulover** [comment]
How about Libraries - Gui - Custom Controls? To go along with Class_Rebar. Thanks for the indications, btw.

**Comment by joedf** [comment]
Hmmmm, yes good idea! :+1:
