### ISSUE TITLE
New Item: Eval

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#84]
### Item to be added:
`Eval`

### Author of the new item
[Pulover](https://github.com/Pulover)

### Awesome-AHK chapter the item should be added to 
`Libraries - Maths`

### Description of the new Item
Evaluate expressions in strings.

### Discussion Links:
Https://autohotkey.Com/boards/viewtopic.Php?F=6&t=13565

### Source Links: 
Https://github.Com/pulover/eval

**Comment by joedf** [comment]
Great :+1:
