### ISSUE TITLE
New Item: CbAutoComplete

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#85]
### Item to be added:
`CbAutoComplete`

### Author of the new item
[Pulover](https://github.com/Pulover)

### Awesome-AHK chapter the item should be added to 
`Libraries - GUI - ComboBox`

### Description of the new Item
Auto-completes typed values in an AHK ComboBox.

### Discussion Links:
https://autohotkey.Com/boards/viewtopic.Php?F=6&t=15002

### Source Links: 
Https://github.Com/pulover/cbautocomplete

**Comment by joedf** [comment]
Approved :+1:
Just watch out for the uppercase characters in the URLs.

**Comment by hoppfrosch** [comment]
Concerning uppercase: It was my clipboard manager who converted to lowercase ... not me ;-)

**Comment by joedf** [comment]
Ahh okay, haha :)
