### ISSUE TITLE
New Item: Checksums

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#86]
### Item to be added:

Checksums
### Author of the new item

Bentschi, Skan, just me, IsNull, jNizM
### Awesome-AHK chapter the item should be added to

Libraries - Maths
### Description of the new Item

Collection of funtions to calculate:
- cheksum from string / hex / file
- HMAC
- Salt
### Discussion Links:

https://autohotkey.com/boards/viewtopic.php?f=6&t=21
### Source Links:

https://github.com/jNizM/AutoHotkey_Scripts/tree/master/Functions/Checksums

**Comment by hi5** [comment]
Wouldn't this be as / more useful https://github.com/ahkscript/LibCrypt.ahk :grey_question:

**Comment by hoppfrosch** [comment]
Thanks for your response/suggestion - that's what I hope for when I suggest a new item to add as a new issue here - with the label discussion ;-). Else if there's no reaction from other board members I'm gonna add my suggestion after a certain period of time.

I haven't seen/noticed this library before (or haven't remebered it). As I was searching for SHA-256 on the forum I found jNizM's collection, which satisfied my needs ... and as no crypt library was on our list yet, I suggested this one.

You might be right: as joedf's library has included jNizM's functions we probably use joedf's one, as
 - it offers more functionality
 - it seems to be newer
 - it's an enclosed library, whereas jNitM's functions are part of a more general collection 

But I don't mind ...

**Comment by joedf** [comment]
I see that both could be included, but simply mention in the description the availability of alternatives.

**Comment by hoppfrosch** [comment]
Really both? It seems thy [https://github.com/ahkscript/LibCrypt.ahk ](https://github.com/ahkscript/LibCrypt.ahk ) includes [https://github.com/jNizM/AutoHotkey_Scripts/tree/master/Functions/Checksums](https://github.com/jNizM/AutoHotkey_Scripts/tree/master/Functions/Checksums) - at least the comments on libcrypt say this ....

**Comment by joedf** [comment]
Hmm... Maybe you're right. Then I would put only libcrypt.ahk, as it mentions everyone's contributions.

**Comment by hoppfrosch** [comment]
As there were no more objections, libcrypt should be added
