### ISSUE TITLE
Update Item: Sparrow

### ISSUE THREAD

**Issue by hoppfrosch** [ahkscript/awesome-AutoHotkey#95]
### Item to be updated:
historical\sparrow

### Update:
Download link to https://github.com/ahkscript/awesome-AutoHotkey/files/219680/sparrow-0.1.3.zip as original download location is not available anymore (see #89)

**Comment by joedf** [comment]
Awesome :+1:

**Comment by hoppfrosch** [comment]
LOL :-)
